name = "LeanSudoku"
version = "0.1.0"
defaultTargets = ["leansudoku"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "LeanSudoku"

[[lean_exe]]
name = "leansudoku"
root = "Main"
